export const mockMetas = [
  {
    id: "meta_1",
    titulo: "Economizar para viagem",
    descricao: "Juntar dinheiro para uma viagem internacional",
    categoria: "Viagem",
    valorTotal: 10000,
    valorParcela: 1000,
    numParcelas: 10,
    recorrente: true,
    frequencia: "mensal",
    diaVencimento: 15,
    dataInicio: "2025-01-01",
    dataFim: "2025-10-01",
    numExecucoes: null,
    usuarioCriadorId: "user_1",
    participantes: ["user_1", "user_2"],
    dataCriacao: "2025-01-01T00:00:00.000Z",
    parcelas: [
      {
        id: "parcela_1",
        metaId: "meta_1",
        numero: 1,
        valor: 1000,
        dataVencimento: "2025-01-15",
        status: "Paga",
        valorPago: 1000,
        responsavel: "usuario1",
        dataPagamento: "2025-01-16",
      },
      {
        id: "parcela_2",
        metaId: "meta_1",
        numero: 2,
        valor: 1000,
        dataVencimento: "2025-02-15",
        status: "Paga",
        valorPago: 1000,
        responsavel: "usuario2",
        dataPagamento: "2025-02-16",
      },
      {
        id: "parcela_3",
        metaId: "meta_1",
        numero: 3,
        valor: 1000,
        dataVencimento: "2025-03-15",
        status: "Pendente",
        valorPago: null,
        responsavel: "usuario1",
        dataPagamento: null,
      },
    ],
  },
  {
    id: "meta_2",
    titulo: "Comprar um carro novo",
    descricao: "Economizar para comprar um carro novo",
    categoria: "Automóvel",
    valorTotal: 50000,
    valorParcela: 5000,
    numParcelas: 10,
    recorrente: false,
    frequencia: null,
    diaVencimento: null,
    dataInicio: "2025-01-01",
    dataFim: "2025-10-01",
    numExecucoes: null,
    usuarioCriadorId: "user_2",
    participantes: ["user_2"],
    dataCriacao: "2025-01-01T00:00:00.000Z",
    parcelas: [
      {
        id: "parcela_1",
        metaId: "meta_2",
        numero: 1,
        valor: 5000,
        dataVencimento: "2025-01-15",
        status: "Pendente",
        valorPago: null,
        responsavel: "usuario2",
        dataPagamento: null,
      },
    ],
  },
];
